# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "push-to-ftp"
  push-to-ftp:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository code
        uses: actions/checkout@v2
        with: 
          token: ${{ github.token }}
      - uses: temeasd/ftp-deployer@v1.4.32
        name: FTP Deployer      
        with:
          sftp: true # optional
          host: ${{ secrets.FTP_HOST }} # e.g. ftp.host.com or sftp.host.com (without ftp:// or ftps://)
          port: 22 # optional, default is: 21
          username: ${{ secrets.FTP_USERNAME }} # FTP username
          password: ${{ secrets.FTP_PASSWORD }} # FTP password
          remote_folder: ${{ secrets.FTP_REMOTE_FOLDER }} # optional, remote path of your FTP server
          local_folder: ./ # optional, local path, default is: dist
          cleanup: false # optional, remove existing files inside FTP remote folder
          include: "* **/*"
          exclude: "**/.git* **/.git*/** */.git* **/node_modules/** **/test* **/LICENCE* **/docker-compose.yml"
          passive: true # optional
